### ISSUE TITLE
Where did Faithful PE go in Curse?

### ISSUE THREAD

**Issue by Johnmacrocraft** [XVTEAM/FaithfulPE#1]
Same with the title, where did it go? I can't find it in Curse.

**Comment by Johnmacrocraft** [comment]
@xMrVizzy

**Comment by xMrVizzy** [comment]
I removed in Curse

**Comment by Johnmacrocraft** [comment]
@xMrVizzy Am I allowed to continue Faithful PE on my GitHub organization? I know there's MCPE DL version of Faithful PE which seems to be more popular than this one, but they haven't updated some textures, while I did.

**Comment by Johnmacrocraft** [comment]
@xMrVizzy Also, may I ask why you removed it on Curse?

**Comment by xMrVizzy** [comment]
because i won't to update it, I can create project again If all need this

**Comment by Johnmacrocraft** [comment]
@xMrVizzy (Sorry for keep commenting) Yay, official Faithful PE is back, thank you.
(You need to update map icon and nether brick texture. Map Icon file has more icons than pc version, and PE nether brick has brighter texture than PC version.)

**Comment by Johnmacrocraft** [comment]
@xMrVizzy Wait, you already updated map icon on last commit. My bad.

**Comment by Johnmacrocraft** [comment]
@xMrVizzy You forgot to update bed (files on entity folder | P.S: (Like you know,) bed texture is sightly different than PC version), steve, alex, and probably much more. I'll bring you list of files that aren't updated or create pull request.

**Comment by Johnmacrocraft** [comment]
@xMrVizzy This project shouldn't be discontinued again as (like you know,) Minecraft will be one platform (not PC).

**Comment by xMrVizzy** [comment]
Yeah soon update
